- name: Run borg backup
  hosts: gruppe1
  vars:
    repo: "borguser@185.11.255.201:/srv/borg/repos"
    source: "/home/debian/testdata/"
  tasks:
    - name: Ensure Borg is installed
      apt:
        name: borgbackup
        state: present
        update_cache: true
      become: true
    - name: Add Borg server to known_hosts
      known_hosts:
        name: 185.11.255.201
        key: "{{ lookup('pipe', 'ssh-keyscan -H 185.11.255.201') }}"
        path: ~/.ssh/known_hosts
      become: true
    - name: Ensure testdata directory exists
      file:
        path: /home/debian/testdata
        state: directory
        owner: debian
        group: debian
        mode: '0755'

    - name: Download file only if it doesn't exist
      get_url:
        url: https://releases.ubuntu.com/24.04.2/ubuntu-24.04.2-desktop-amd64.iso
        dest: "{{ source }}/testfile"
        force: false
        mode: '0755'

    - name: Init Borg repo
      shell: borg init --encryption=none "{{ repo }}/client1{{ borg_id }}"
      ignore_errors: true
      register: result

    - name: Run Borg backup
      shell: borg create --stats "{{ repo }}/client1{{ borg_id }}::test_client{{ borg_id }}" "{{ source }}"
      ignore_errors: true
      register: borg_output

    - name: Show stderr
      debug:
        msg: "{{ borg_output.stderr_lines }}"
