location:
  source_directories:
    - /home/username
    - /etc
  repositories:
    - borg-server:/srv/borg/repos/client1

storage:
  encryption_passphrase: "optional-if-needed"

retention:
  keep_hourly: 24
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 12
  keep_yearly: 3

consistency:
  checks:
    - repository
    - archives
  check_last: 3

hooks:
  before_backup:
    - echo "Starting backup..."
  after_backup:
    - echo "Backup complete. Starting restore test..."
    - mkdir -p /tmp/borgmatic-restore-test
    - borgmatic extract --archive latest --destination /tmp/borgmatic-restore-test --paths etc/hostname
    - test -f /tmp/borgmatic-restore-test/etc/hostname && echo "Restore test passed." || echo "Restore test failed!"
    - rm -rf /tmp/borgmatic-restore-test
